<?php

namespace Ibtdi\HiSms\Tests;

use Ibtdi\HiSms\HISmsServiceProvider;
use Orchestra\Testbench\TestCase as OrchestraTestCase;
class TestCase extends OrchestraTestCase
{
    protected function getPackageProviders($app): array
	{
		return [
			HISmsServiceProvider::class,
		];
	}
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
    }

}
